import { db } from './firebase.js';import { requireAdmin } from './auth-guard.js';import { collection,addDoc,getDocs,updateDoc,deleteDoc,doc,serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const $=id=>document.getElementById(id), f=$('entryForm'), tbody=$('tbody'), status=$('status');let rows=[],editId=null;const num=v=>Number(v||0),money=v=>'₹'+num(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));const show=(m,t='info')=>{status.textContent=m;status.className=`status show ${t}`};
function calc(){ $('due').value=Math.max(0,num($('total').value)-num($('paid').value)).toFixed(2)}
function reset(){editId=null;f.reset();$('date').value=new Date().toISOString().slice(0,10);$('paid').value=0;calc();$('saveBtn').textContent='Save'}
async function load(){show('Records loading...');const snap=await getDocs(collection(db,'customers'));rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.date).localeCompare(String(a.date)));render();show('Records loaded','ok')}
function render(){const q=$('search').value.toLowerCase(),fs=$('filterStatus').value;const list=rows.filter(x=>(!fs||x.workStatus===fs)&&[x.name,x.mobile,x.service].join(' ').toLowerCase().includes(q));tbody.innerHTML=list.length?list.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.name)}</td><td>${esc(x.mobile)}</td><td>${esc(x.service)}</td><td>${money(x.total)}</td><td>${money(x.paid)}</td><td>${money(x.due)}</td><td>${esc(x.workStatus)}</td><td class="no-print"><button class="btn light edit" data-id="${x.id}">Edit</button> <button class="btn danger del" data-id="${x.id}">Delete</button></td></tr>`).join(''):'<tr><td class="empty" colspan="9">No records</td></tr>';const total=rows.reduce((s,x)=>s+num(x.total),0),paid=rows.reduce((s,x)=>s+num(x.paid),0),due=rows.reduce((s,x)=>s+num(x.due),0);$('count').textContent=rows.length;$('totalSum').textContent=money(total);$('paidSum').textContent=money(paid);$('dueSum').textContent=money(due)}
f.addEventListener('submit',async e=>{e.preventDefault();const data={date:$('date').value,name:$('name').value.trim(),mobile:$('mobile').value.trim(),service:$('service').value.trim(),total:num($('total').value),paid:num($('paid').value),due:num($('due').value),workStatus:$('workStatus').value,note:$('note').value.trim(),updatedAt:serverTimestamp()};try{show('Saving...');if(editId)await updateDoc(doc(db,'customers',editId),data);else await addDoc(collection(db,'customers'),{...data,createdAt:serverTimestamp()});reset();await load()}catch(e){show(e.message,'error')}});
tbody.addEventListener('click',async e=>{const id=e.target.dataset.id;if(!id)return;if(e.target.classList.contains('edit')){const x=rows.find(r=>r.id===id);editId=id;['date','name','mobile','service','total','paid','workStatus','note'].forEach(k=>$(k).value=x[k]??'');calc();$('saveBtn').textContent='Update';scrollTo({top:0,behavior:'smooth'})}if(e.target.classList.contains('del')&&confirm('यह रिकॉर्ड हटाएँ?')){await deleteDoc(doc(db,'customers',id));await load()}});
['total','paid'].forEach(id=>$(id).addEventListener('input',calc));$('search').addEventListener('input',render);$('filterStatus').addEventListener('change',render);$('clearBtn').addEventListener('click',reset);$('printBtn').addEventListener('click',()=>print());$('csvBtn').addEventListener('click',()=>{const lines=[['Date','Name','Mobile','Service','Total','Paid','Due','Status'],...rows.map(x=>[x.date,x.name,x.mobile,x.service,x.total,x.paid,x.due,x.workStatus])];const csv=lines.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='customer-diary.csv';a.click()});requireAdmin(()=>{reset();load().catch(e=>show(e.message,'error'))});
