import { db } from './firebase.js';import { requireAdmin } from './auth-guard.js';import { collection,addDoc,getDocs,updateDoc,deleteDoc,doc,serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const $=id=>document.getElementById(id),f=$('entryForm'),tbody=$('tbody'),status=$('status');let rows=[],editId=null;const n=v=>Number(v||0),money=v=>'₹'+n(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));const show=(m,t='info')=>{status.textContent=m;status.className=`status show ${t}`};
function calc(){const total=n($('quantity').value)*n($('rate').value);$('total').value=total.toFixed(2);$('due').value=Math.max(0,total-n($('paid').value)).toFixed(2)}
function reset(){editId=null;f.reset();$('date').value=new Date().toISOString().slice(0,10);$('paid').value=0;calc();$('saveBtn').textContent='Save'}
async function load(){show('Milk records loading...');const snap=await getDocs(collection(db,'milkRecords'));rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.date).localeCompare(String(a.date)));render();show('Milk records loaded','ok')}
function filtered(){const q=$('search').value.toLowerCase(),m=$('monthFilter').value;return rows.filter(x=>(!m||String(x.date).startsWith(m))&&[x.customerName,x.mobile].join(' ').toLowerCase().includes(q))}
function render(){const list=filtered();tbody.innerHTML=list.length?list.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.customerName)}</td><td>${esc(x.mobile)}</td><td>${esc(x.shift)}</td><td>${esc(x.milkType)}</td><td>${n(x.quantity).toFixed(2)} L</td><td>${money(x.rate)}</td><td>${money(x.total)}</td><td>${money(x.paid)}</td><td>${money(x.due)}</td><td class="no-print"><button class="btn light edit" data-id="${x.id}">Edit</button> <button class="btn danger del" data-id="${x.id}">Delete</button></td></tr>`).join(''):'<tr><td class="empty" colspan="11">No records</td></tr>';$('count').textContent=list.length;$('milkSum').textContent=list.reduce((s,x)=>s+n(x.quantity),0).toFixed(2)+' L';$('amountSum').textContent=money(list.reduce((s,x)=>s+n(x.total),0));$('dueSum').textContent=money(list.reduce((s,x)=>s+n(x.due),0))}
f.addEventListener('submit',async e=>{e.preventDefault();const data={date:$('date').value,customerName:$('customerName').value.trim(),mobile:$('mobile').value.trim(),shift:$('shift').value,milkType:$('milkType').value,quantity:n($('quantity').value),rate:n($('rate').value),total:n($('total').value),paid:n($('paid').value),due:n($('due').value),updatedAt:serverTimestamp()};try{show('Saving...');if(editId)await updateDoc(doc(db,'milkRecords',editId),data);else await addDoc(collection(db,'milkRecords'),{...data,createdAt:serverTimestamp()});reset();await load()}catch(e){show(e.message,'error')}});
tbody.addEventListener('click',async e=>{const id=e.target.dataset.id;if(!id)return;if(e.target.classList.contains('edit')){const x=rows.find(r=>r.id===id);editId=id;['date','customerName','mobile','shift','milkType','quantity','rate','paid'].forEach(k=>$(k).value=x[k]??'');calc();$('saveBtn').textContent='Update';scrollTo({top:0,behavior:'smooth'})}if(e.target.classList.contains('del')&&confirm('यह दूध रिकॉर्ड हटाएँ?')){await deleteDoc(doc(db,'milkRecords',id));await load()}});
['quantity','rate','paid'].forEach(id=>$(id).addEventListener('input',calc));$('search').addEventListener('input',render);$('monthFilter').addEventListener('change',render);$('allBtn').addEventListener('click',()=>{$('monthFilter').value='';render()});$('clearBtn').addEventListener('click',reset);$('printBtn').addEventListener('click',()=>print());$('csvBtn').addEventListener('click',()=>{const list=filtered(),lines=[['Date','Customer','Mobile','Shift','Type','Quantity','Rate','Total','Paid','Due'],...list.map(x=>[x.date,x.customerName,x.mobile,x.shift,x.milkType,x.quantity,x.rate,x.total,x.paid,x.due])];const csv=lines.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='milk-diary.csv';a.click()});requireAdmin(()=>{reset();load().catch(e=>show(e.message,'error'))});
